AllCops:
#  Include:
#  - 'hello.rb'
  Exclude:
  - 'Gemfile'
  - '.git_hooks/**/*'
  - '.idea'
  - 'buildtasks/*'
  - 'buildtasks/**/*'
Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/SymbolLiteral:
  Enabled: false
Metrics/LineLength:
  Enabled: false
