AllCops:
  Include:
  - 'hello.rb'
  Exclude:
  - 'Gemfile'
Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/SymbolLiteral:
  Enabled: false
Metrics/LineLength:
  Enabled: false
